#  

In [9]:
import numpy as np
x = np.array([4.8,67,57,90])
print(x)
print(type(x))
print(x.dtype)

[ 4.8 67.  57.  90. ]
<class 'numpy.ndarray'>
float64


In [11]:
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)




[[10 20]
 [30 40]]
(2, 2)


In [13]:
c = np.arange(3,20)
print(c)
type(c)



[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [19]:
d = np.array([1.3467,3.10987,4.91236])
np.around(d,2)


array([1.35, 3.11, 4.91])

In [21]:
print(np.sqrt(d))

[1.16047404 1.76348235 2.21638444]


In [23]:
print(np.around(np.sqrt(d),2))

[1.16 1.76 2.22]


In [ ]:
#2D ARRAY

In [25]:
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
a1_copy1 = a1.astype(float)
a1_copy1.dtype



dtype('float64')

In [35]:
a1 = np.array([[3,4,5,8],[7,2,8, np.NAN]])
print(a1)
a1.dtype



[[ 3.  4.  5.  8.]
 [ 7.  2.  8. nan]]


dtype('float64')

In [37]:
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype



[['3.0' '4.0' '5.0' '8.0']
 ['7.0' '2.0' '8.0' 'nan']]


dtype('<U32')

In [39]:
a2 = np.array([[3,4,5],[6,7,8],[1,2,3]])
a2


array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3]])

In [41]:
print(a2.sum(axis = 1))
print(a2.sum(axis = 0))


[12 21  6]
[10 13 16]


In [43]:
print(a2)
print(np.mean(a2, axis = 1))
print(np.mean(a2, axis = 0))

[[3 4 5]
 [6 7 8]
 [1 2 3]]
[4. 7. 2.]
[3.33333333 4.33333333 5.33333333]


In [45]:
a3 = np.array([[3,4,5],[6,7,8],[1,2,3]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)




[[3 4 5]
 [6 7 8]
 [1 2 3]]
[[0 4 5]
 [6 0 8]
 [1 2 0]]


In [55]:
A = np.array([[3,4],[1,2]])
B = np.array([[6,2],[7,2]])
C = np.matmul(A, B)
C


array([[46, 14],
       [20,  6]])

In [57]:
print(A. T)
print(B. T)


[[3 1]
 [4 2]]
[[6 7]
 [2 2]]


In [63]:
 a4 = np.array([[3,4,5],[6,7,8],[1,2,3],[7,9,1]])
a4


array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [7, 9, 1]])

In [61]:
a4[0::3,0::2]

array([[3, 5]])

In [67]:
#slicing of the array
a4[1:3]


array([[6, 7, 8],
       [1, 2, 3]])

In [ ]:
# create pandas series

In [5]:
import pandas as pd

In [13]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [19]:
data = [1,2,3,4]
i = ['A', 'B', 'C', 'D']
series = pd.Series(data, index=i)
print(series)




A    1
B    2
C    3
D    4
dtype: int64


In [25]:
data = {'a':10, 'b':20, 'c':30}
series = pd.Series(data)
print(series)



a    10
b    20
c    30
dtype: int64


In [27]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [39]:
import pandas as np
data = np.array([100,200,300])
df = pd.DataFrame(data)
print(df)





     0
0  100
1  200
2  300


In [33]:
import pandas as pd

In [37]:
data = {'Name':['Alice', 'Bob', 'Mary'], 'Age':[25, 30, 34], 'Country':['USA', 'UK', 'LA']}
df=pd.DataFrame(data)
print(df)



    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34      LA


In [45]:
import numpy as np
array = np.array([[3,4,5],[6,7,8],[1,2,3]])
print(array)
df=pd.DataFrame(array, columns=['A', 'B', 'C'])
print(df)


[[3 4 5]
 [6 7 8]
 [1 2 3]]
   A  B  C
0  3  4  5
1  6  7  8
2  1  2  3
